os: linux
dist: trusty
python:
    - '3.6'
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y cpanminus ghc libperl-dev python3 python3-setuptools perl python3-pip
install:
    - which python3
    - python3 --version
    - sudo -H `which python3` -m pip install flake8 pycotap
    - sudo cpanm --notest File::Which String::ShellQuote Test::Differences Test::TrailingSpace
    - cabal update
    - cabal install mtl
perl:
    - "5.26"
script:
    - make test
